---
# - hosts: k8s-node
#   remote_user: root
#   tasks:
#     - name: copy node*bin to any node
#       copy:
#         src: "{{ item.src }}"
#         dest: "{{ item.dest }}"
#         mode: "{{ item.mode }}"
#       with_items:
#         - { src: './file/client/kubectl',dest: '/usr/local/sbin/',mode: '0755'}
#         - { src: './file/server/kubernetes/server/bin/kubelet', dest: '/usr/local/sbin/',mode: '0755'}
#         - { src: './file/server/kubernetes/server/bin/kube-proxy', dest: '/usr/local/sbin/',mode: '0755'}
#     - name: copy node*config to node
#       copy:
#         src: "{{ item.src }}"
#         dest: "{{ item.dest }}"
#         mode: "{{ item.mode }}"
#       with_items:
#         - { src: './config/config',dest: '/etc/kubernetes/',mode: '0644'}
#         - { src: './config/kubelet.service',dest: '/lib/systemd/system/',mode: '0644'}
#         - { src: './config/kubelet',dest: '/etc/kubernetes/',mode: '0644'}
#         - { src: './config/kubelet.kubeconfig',dest: '/etc/kubernetes/',mode: '0644'}
#         - { src: './config/kube-proxy.service',dest: '/lib/systemd/system/',mode: '0644'}
#         - { src: './config/kube-proxy',dest: '/etc/kubernetes/',mode: '0644'}
#     - name: create dir
#       file:
#         path: "{{ item.path }}"
#         state: "{{ item.state }}"
#       with_items:
#         - { path: '/logs/kubernetes',state: 'directory'}
#         - { path: '/var/lib/kubelet',state: 'directory'}
#         - { path: '/etc/kubernetes/manifests',state: 'directory'}
#     - name: start node
#       shell:
#         systemctl daemon-reload && systemctl start kubelet.service &&
#         systemctl start kube-proxy.service

- hosts: k8s-master
  remote_user: root
  tasks:
    # - name: copy master*bin to master
    #   copy:
    #     src: "{{ item.src }}"
    #     dest: "{{ item.dest }}"
    #     mode: "{{ item.mode }}"
    #   with_items:
    #     - { src: './file/server/kubernetes/server/bin/kube-apiserver', dest: '/usr/local/sbin/',mode: '0755'}
    #     - { src: './file/server/kubernetes/server/bin/kube-controller-manager', dest: '/usr/local/sbin/',mode: '0755'}
    #     - { src: './file/server/kubernetes/server/bin/kube-scheduler', dest: '/usr/local/sbin/',mode: '0755'}

    - name: copy master*config to master
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items:
        # - { src: './config/config',dest: '/etc/kubernetes/',mode: '0644'}
        # - { src: './config/kube-apiserver.service',dest: '/lib/systemd/system/',mode: '0644'}
        # - { src: './config/kube-apiserver',dest: '/etc/kubernetes/',mode: '0644'}
        - { src: './config/kube-controller-manager.service',dest: '/lib/systemd/system/',mode: '0644'}
        - { src: './config/kube-controller-manager',dest: '/etc/kubernetes/',mode: '0644'}
        # - { src: './config/kube-scheduler.service',dest: '/lib/systemd/system/',mode: '0644'}
        # - { src: './config/kube-scheduler',dest: '/etc/kubernetes/',mode: '0644'}
#
    - name: create dir
      file: path=/logs/kubernetes state=directory
#
    - name: start master
      shell:
        systemctl daemon-reload && systemctl restart kube-controller-manager.service
        # systemctl start kube-apiserver.service && \
        # systemctl start kube-scheduler.service
