apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-alertmanager
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: k8s-alertmanager.xingshulin.com
    http:
      paths:
      - backend:
          serviceName: monitor-prometheus-alertmanager
          servicePort: 9093
  tls:
    - hosts:
        - k8s-alertmanager.xingshulin.com
      secretName: example-tls

