apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-prometheus
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/app-root: "graph"
spec:
  rules:
  - host: k8s-promethues.xingshulin.com
    http:
      paths:
      - backend:
          serviceName: monitor-prometheus-server
          servicePort: 9090
  tls:
    - hosts:
        - k8s-promethues.xingshulin.com
      secretName: example-tls

