apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: k8s-grafana.xingshulin.com
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
  tls:
    - hosts:
        - k8s-grafana.xingshulin.com
      secretName: example-tls

