alertmanager:
  persistentVolume:
    enabled: false
  service:
    type: NodePort
    nodePort: 30003

server:
  persistentVolume:
    enabled: false
  service:
    type: NodePort
    nodePort: 30002

pushgateway:
  enabled: false

kubeStateMetrics:
  image:
    repository: mirrorgooglecontainers/kube-state-metrics
