---
- hosts: k8s-master
  remote_user: root
  tasks:
    - name: copy master二进制执行程序到 master 节点
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items:
        - { src: './file/server/bin/kubectl',dest: '/usr/local/sbin/',mode: '0755'}
        - { src: './file/server/bin/kube-apiserver', dest: '/usr/local/sbin/',mode: '0755'}
        - { src: './file/server/bin/kube-controller-manager', dest: '/usr/local/sbin/',mode: '0755'}
        - { src: './file/server/bin/kube-scheduler', dest: '/usr/local/sbin/',mode: '0755'}

    - name: copy k8s集群证书和服务配置cd 文件 to master
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items:
        - { src: './gen-ca/ssl',dest: '/etc/kubernetes/',mode: '0644'}
        - { src: './gen-ca/ssl-conf',dest: '/etc/kubernetes/',mode: '0644'}
        - { src: './config/config',dest: '/etc/kubernetes/',mode: '0644'}
        - { src: './config/token.csv',dest: '/etc/kubernetes/',mode: '0644'}

        - { src: './config/kube-apiserver.service',dest: '/lib/systemd/system/',mode: '0644'}
        - { src: './config/kube-apiserver',dest: '/etc/kubernetes/',mode: '0644'}
        - { src: './config/kube-controller-manager.service',dest: '/lib/systemd/system/',mode: '0644'}
        - { src: './config/kube-controller-manager',dest: '/etc/kubernetes/',mode: '0644'}
        - { src: './config/kube-scheduler.service',dest: '/lib/systemd/system/',mode: '0644'}
        - { src: './config/kube-scheduler',dest: '/etc/kubernetes/',mode: '0644'}
    - name: create dir
      file: path=/logs/kubernetes state=directory
    #
    - name: start master
      shell:
        systemctl daemon-reload &&
        systemctl restart kube-apiserver.service
        # systemctl start kube-controller-manager.service &&
        # systemctl start kube-scheduler.service

    # - name: 为部署启动node节点准备
    #   shell:
    #     cd /etc/kubernetes &&
    #     kubectl create clusterrolebinding kubelet-bootstrap \
    #       --clusterrole=system:node-bootstrapper \
    #       --user=kubelet-bootstrap
